<?php
	/**
	 *实现hook_menu
	*/
	function keti_menu(){
		$items['keti']=array(
			'title'=>'在线选题',
			'description'=>'实现在线选题',
			'page callback'=>'keti_callback_page',
			'type'=>MENU_CALLBACK,
			'file'=>'keti.pages.inc',
			'access callback'=>TRUE,
		);
		$items['keti/confirm']=array(
			'page callback'=>'keti_confirm_callback_page',
			'type'=>MENU_CALLBACK,
			'file'=>'keti.pages.inc',
			'access callback'=>TRUE,
		);
		return $items;
	}
