#!/bin/sh


 /bin/ls -a > /home/laoning/proj1/gp2012/lining/file
 


#git pull 
git init 
git commit -a -m "my folder" 
git push 


#echo hello >> /home/laoning/proj1/gp2012/lining/file-tmp
#echo `date` >> /home/laoning/proj1/gp2012/lining/file-tmp
