#!/bin/sh
cd /home/laoning/laoning
echo hello >> /home/laoning/laoning/file-tmp1
echo `date` >> /home/laoning/laoning/file-tmp1 //测试脚本文件是否定时执行

#git pull

if make
  then
     echo `date` >>consequence.txt  //输出日期
     echo  program is right! >>consequence.txt  //输出程序运行结果
     mutt -s "TITLE: Compile Result" 835742268@qq.com -a /home/laoning/laoning/consequence.txt
     #mutt -s "TITLE: Compile Result" 779371162@qq.com -a /home/laoning/laoning/consequence.txt 
else
     echo `date` >>consequence.txt
     echo  there is an error! >>consequence.txt
     mutt -s "TITLE: Compile Result" 835742268@qq.com -a /home/laoning/laoning/consequence.txt
     #mutt -s "TITLE: Compile Result" 779371162@qq.com -a /home/laoning/laoning/consequence.txt 
fi

