#!/bin/sh
#/bin/ls -a /home/laoning/proj1/gp2012 > /home/laoning//proj1/gp2012/lining/temp

 #/bin/ls -a > /home/laoning/proj1/gp2012/lining/file
 #/bin/cp /home/laoning/proj1/gp2012/lining/file /home/laoning/proj1/gp2012/lining/file1



#git init /home/laoning/proj1/gp2012
#git add /home/laoning/proj1/gp2012/lining 
#git commit -m "my folder" /home/laoning/proj1/gp2012
#git pull /home/laoning/proj1/gp2012
#git push /home/laoning/proj1/gp2012


#echo hello >> /home/laoning/proj1/gp2012/lining/file-tmp
#echo `date` >> /home/laoning/proj1/gp2012/lining/file-tmp
