#!/bin/sh

 /bin/ls -a > /home/laoning/proj1/gp2012/lining/file
 /bin/cp /home/laoning/proj1/gp2012/lining/file /home/laoning/proj1/gp2012/lining/file1

/bin/cd /home/laoning//proj1/gp2012
git init
git add lining
git commit -m "my folder"
git push


#echo hello >> /home/laoning/proj1/gp2012/lining/file-tmp
#echo `date` >> /home/laoning/proj1/gp2012/lining/file-tmp
