#!/bin/sh


ls -a > /home/laoning/laoning/file
 
echo hello >> /home/laoning/laoning/file-tmp
echo `date` >> /home/laoning/laoning/file-tmp

cd /home/laoning/laoning 
git init 
git add -A
git commit -m "my experiment" 
git push 


